### ISSUE TITLE
Issue installing with Python 3.12.5

### ISSUE THREAD

**Issue by cedschmidt-lab** [SPF-OST/pytrnsys#207]
Dear helpers,

I'm struggling installing pytrnsys following your steps. 

I'm working on Windows 10 pro with Python 3.12.5.

The venv is correctly created and wheel package installed, but when running this line:
`pip install -r https://raw.githubusercontent.com/SPF-OST/pytrnsys/v0.6.4-reqs/requiements/releases/v0.6.4/requirements.txt
`
I get:
```
Collecting attrs==20.3.0 (from -r https://raw.githubusercontent.com/SPF-OST/pytrnsys/v0.6.4-reqs/requirements/releases/v0.6.4/requirements.txt (line 7))
  Using cached attrs-20.3.0-py2.py3-none-any.whl.metadata (10 kB)
Collecting bokeh==2.3.0 (from -r https://raw.githubusercontent.com/SPF-OST/pytrnsys/v0.6.4-reqs/requirements/releases/v0.6.4/requirements.txt (line 9))
  Using cached bokeh-2.3.0.tar.gz (10.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      C:\Users\Invite\AppData\Local\Temp\pip-install-i7h5i5xc\bokeh_464c7254c5b146559c5f663057da029d\versioneer.py:419: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "D:\FlexiGEO\pytrnsys\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\FlexiGEO\pytrnsys\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\FlexiGEO\pytrnsys\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Invite\AppData\Local\Temp\pip-build-env-e3vv_eh4\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Invite\AppData\Local\Temp\pip-build-env-e3vv_eh4\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "C:\Users\Invite\AppData\Local\Temp\pip-build-env-e3vv_eh4\overlay\Lib\site-packages\setuptools\build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\Invite\AppData\Local\Temp\pip-build-env-e3vv_eh4\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 108, in <module>
        File "C:\Users\Invite\AppData\Local\Temp\pip-install-i7h5i5xc\bokeh_464c7254c5b146559c5f663057da029d\versioneer.py", line 1475, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "C:\Users\Invite\AppData\Local\Temp\pip-install-i7h5i5xc\bokeh_464c7254c5b146559c5f663057da029d\versioneer.py", line 1407, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Invite\AppData\Local\Temp\pip-install-i7h5i5xc\bokeh_464c7254c5b146559c5f663057da029d\versioneer.py", line 340, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1

╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I tried downgrading to Python 3.11 and 3.10 without success (other errors).

Can you suggest something?

Bests,

**Comment by zuckerruebe** [comment]
Hi

Thanks for getting in touch. I'd suggest using the latest version of `pytrnsys`, i.e. replace step 6 in the installation instructions with 
```pip install -r https://raw.githubusercontent.com/SPF-OST/pytrnsys/master/requirements/release.txt```.

I'd suggest restarting the whole installation process from step one but use the "modified" step 6.

In general, depending on your use case, it might be easier to just install/download the pytrnsys GUI (which includes plain pytrnsys) from here: https://github.com/SPF-OST/pytrnsys_gui/releases/tag/bleeding-edge.

What are you planning to do with `pytrnsys` if I may ask?
